package com.history.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.ProgressBar;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class TestFormDesign extends VerticalLayout {
    protected Label questionNumber;
    protected ProgressBar progress;
    protected Label question;
    protected CheckBox ansver1;
    protected CheckBox ansver2;
    protected CheckBox ansver3;
    protected CheckBox ansver4;
    protected Button back;
    protected Button forvard;

    public TestFormDesign() {
        Design.read(this);
    }
}
